accuracy: 0.9952380952380953
best_max_depth: 10
best_n_estimators: 382
feature_weights:
- 0.8138780765150273
- 1.1910558127392616
- 0.7716331812743696
- 0.6906098330744498
model: Hybrid_HSA_AIS_RandomForest
